[package]
name = "ezgame"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

[dependencies]
winit = "0.22.2"
legion = "0.2.4"

ezgfx = { path = "../ezgfx", optional = true }

[features]
#default = ["plugin-ezgfx"]
plugin-ezgfx = ["ezgfx"]