[package]
name = "voxels"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"


[dependencies]
ezgame = { path = "../ezgame" }
ezmath = { path = "../ezmath" }

dashmap = "3.11.4"
noise = "0.6.0"

[features]
default = ["ezgame/plugin-ezgfx"]