[package]
name = "voxels"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

[dependencies]
pixels = "0.0.4"
nalgebra = "0.21.0"
rayon = "1.3.0"
winit = "0.22.2"
winit_input_helper = "0.6.0"
image = "0.23.4"
noise = "0.6.0"
rand = "0.7.3"